name: Magisk Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: macos-26
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Replace package name in stub build file
        run: |
          sed -i '' 's/com\.topjohnwu\.magisk/you.know.what.iam.saying/g' app/stub/build.gradle.kts
          find app/stub/src/main/java/ -name "*.java" -exec sed -i '' 's/com\.topjohnwu\.magisk\./you.know.what.iam.saying./g' {} \;

      - name: Build release
        run: ./build.py -vr all

      # - name: Build debug
      #   run: ./build.py -v all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}-symbols
          path: app/apk/build/outputs
          compression-level: 9
