name: Magisk Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: macos-26
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Replace package name in stub build file
        run: |
          sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' app/core/build.gradle.kts
          sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' app/stub/build.gradle.kts
          find app/stub/src/main/java/ -type f -name "*.java" -exec sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' {} \;
          mv app/stub/src/main/java/com/topjohnwu/magisk app/stub/src/main/java/com/topjohnwu/know
          mv app/stub/src/main/java/com/topjohnwu app/stub/src/main/java/com/you

          find app/core  -type f -exec sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' {} \;
          mv app/core/src/main/java/com/topjohnwu/magisk app/core/src/main/java/com/topjohnwu/know
          mv app/core/src/main/aidl/com/topjohnwu/magisk app/core/src/main/aidl/com/topjohnwu/know
          mv app/core/src/main/java/com/topjohnwu app/core/src/main/java/com/you
          mv app/core/src/main/aidl/com/topjohnwu app/core/src/main/aidl/com/you

          find app/stub/src/main/java/ -type f -exec sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' {} \;
          mv app/shared/src/main/java/com/topjohnwu/magisk app/shared/src/main/java/com/topjohnwu/know
          mv app/shared/src/main/java/com/topjohnwu app/shared/src/main/java/com/you
          
          
          find app/test/ -type f -name '*.kt*' -exec sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' {} \;
          find app/build-logic/ -type f -name '*.kt*' -exec sed -i '' 's/com\.topjohnwu\.magisk/com.you.know/g' {} \;

          #sed -i '' 's/applicationId = "com\.topjohnwu\.magisk/applicationId = "you.know.what.iam.saying/g' app/stub/build.gradle.kts
          #cat app/stub/build.gradle.kts
          #find app/stub/src/main/java/ -name "*.java" -exec sed -i '' 's/import static com\.topjohnwu\.magisk\./import static you.know.what.iam.saying./g' {} \;

      - name: Build release
        run: ./build.py -vr all

      # - name: Build debug
      #   run: ./build.py -v all
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()
        
      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.sha }}-symbols
          path: app/apk/build/outputs
          compression-level: 9
